// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Parses homeopathic inventory queries and extracts key information such as medicine name, potency, and intent.
 *
 * - parseHomeopathicQuery - A function that handles the parsing process.
 * - ParseHomeopathicQueryInput - The input type for the parseHomeopathicQuery function.
 * - ParseHomeopathicQueryOutput - The return type for the parseHomeopathicQuery function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ParseHomeopathicQueryInputSchema = z.object({
  query: z.string().describe('The natural language query about homeopathic medicines.'),
});

export type ParseHomeopathicQueryInput = z.infer<typeof ParseHomeopathicQueryInputSchema>;

const ParseHomeopathicQueryOutputSchema = z.object({
  medicineName: z.string().describe('The name of the homeopathic medicine extracted from the query.'),
  potency: z.string().describe('The potency of the medicine extracted from the query (e.g., 30C, 200X).'),
  intent: z
    .string()
    .describe(
      'The likely intent of the user, such as dispensing the medicine, checking the quantity, or finding more information.'
    ),
});

export type ParseHomeopathicQueryOutput = z.infer<typeof ParseHomeopathicQueryOutputSchema>;

export async function parseHomeopathicQuery(
  input: ParseHomeopathicQueryInput
): Promise<ParseHomeopathicQueryOutput> {
  return parseHomeopathicQueryFlow(input);
}

const parseHomeopathicQueryPrompt = ai.definePrompt({
  name: 'parseHomeopathicQueryPrompt',
  input: {schema: ParseHomeopathicQueryInputSchema},
  output: {schema: ParseHomeopathicQueryOutputSchema},
  prompt: `You are an AI assistant specialized in parsing queries related to homeopathic medicines.
  Your task is to extract the medicine name, potency, and the user's intent from the given query.
  If the query does not specify a potency, assume the user is asking for any potency.

  Query: {{{query}}}

   medicineName: The name of the homeopathic medicine
  potency: The potency of the medicine (e.g., 30C, 200X).
  intent: The likely intent of the user (e.g., dispense, check quantity, find information).

  Respond in JSON format.
`,
});

const parseHomeopathicQueryFlow = ai.defineFlow(
  {
    name: 'parseHomeopathicQueryFlow',
    inputSchema: ParseHomeopathicQueryInputSchema,
    outputSchema: ParseHomeopathicQueryOutputSchema,
  },
  async input => {
    const {output} = await parseHomeopathicQueryPrompt(input);
    return output!;
  }
);
